name: "[Dispatch] Build Dev"

on:
  workflow_dispatch:

permissions:
  checks: read


jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: get current date
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
          echo "TIME=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
      - name: set version with current date
        id: versioning
        run: |
          echo "VERSION=$(sed 's/v//' < src/VERSION).${{ env.TIME }}" >> $GITHUB_OUTPUT

  docker:
      needs: versioning
      runs-on: ubuntu-latest
      env:
        VERSION: ${{ needs.versioning.outputs.version }}
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
  
        - name: get service name
          run: |
            echo "SERVICE=$(echo ${{ github.repository }} | cut -d '/' -f2)" >> $GITHUB_ENV
            
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
  
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            
        - name: Build and push to repository
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true 
            tags: nana0712/plugin-naver-cloud-mon-webhook:${{ env.VERSION }}
            
